apiVersion: v2
name: application
description: Generic helm chart for all kind of applications

type: application

# Helm chart Version

version: 0.2.0


keywords:
  - DevOps
  - kubernetes
  - application

icon: https://static.vegsoc.org/app/uploads/2024/07/shutterstock_2315756181-708x480.jpg
