name: Push

concurrency:
 group: push_on_main
 cancel-in-progress: false

on:
  push:
    branches:
      - main

env:
  CHART_NAME: "application"

jobs:
  helm-dry-run:
    name: helm-dry-run
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Helm
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
    - name: Helm Lint
      run: |
        helm lint charts/${CHART_NAME}
        helm lint charts/${CHART_NAME} -f charts/${CHART_NAME}/values-test.yaml
    - name: Dry Run Chart
      run: |
        helm template ${CHART_NAME} charts/${CHART_NAME} -f charts/${CHART_NAME}/values-test.yaml --debug

  bump-version:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.get_next_version.outputs.version }}
      has_next_version: ${{ steps.get_next_version.outputs.hasNextVersion }}
    if: ${{ vars.RELEASE_CIRCUIT_BREAKER == 'false' }}
    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@067dc4602577f4f61a51c3f4664552283a228c60 # 2.7.1
    - name: Show the next version
      run: |
        echo Has next version: ${{ steps.get_next_version.outputs.hasNextVersion }}
        echo Next version: ${{ steps.get_next_version.outputs.version }}

  push-changes:
    runs-on: ubuntu-latest
    needs:
    - helm-dry-run
    - bump-version
    if: needs.bump-version.outputs.has_next_version == 'true'
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0
    - name: Update Chart Version
      env:
        VERSION: ${{ needs.bump-version.outputs.next_version }}
        CHART: ${{ env.CHART_NAME }}
      run: |
        # Update Chart.yaml version
        sed -i "s/^version: .*/version: ${VERSION}/" charts/${CHART}/Chart.yaml
    - name: Commit updated artifacts
      id: commit
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git status
        git add charts/application/Chart.yaml
        git commit -m "chore: Update artifacts [skip-ci]" --allow-empty
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - name: Push updated artifacts
      uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create tag
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/v${{ needs.bump-version.outputs.next_version }}',
            sha: '${{ steps.commit.outputs.sha }}'
          })
